#!/usr/bin/env ruby

require_relative './lib/commands'
require_relative './lib/library'

library = Library.new

puts 'Welcome to your music collection!'

loop {
  print "> "
  tokens = gets.chomp.scan /(?:\w|"[^"]*")+/

  case tokens.shift
  when 'quit'
    break
  when 'add'
    cmd = Commands::Add.new(library, tokens)
  when 'play'
    cmd = Commands::Play.new(library, tokens)
  when 'show'
    cmd = Commands::Show.new(library, tokens)
  else
    puts 'Valid commands: add, play, show, quit'
    next
  end

  if cmd.valid?
    cmd.execute
  else
    puts cmd.class::SYNTAX
  end
}

puts 'Bye!'
